"""add dtype to descriptors

Revision ID: 4856a6d821b
Revises: None
Create Date: 2018-04-11 18:20:42.412042

"""

# revision identifiers, used by Alembic.
revision = '4856a6d821b'
down_revision = None

from sqlalchemy.orm import sessionmaker, Session as BaseSession, relationship
from app.models import Descriptor
from alembic import op
import sqlalchemy as sa

Session = sessionmaker()

def upgrade():
    bind = op.get_bind()
    session = Session(bind=bind)

    # add d column
    op.add_column('descriptors', sa.Column('dtype', sa.String(length=15), nullable=True))

    # set player team based on team name
    for descriptor in session.query(Descriptor):
        if (descriptor.values is not None):
        	descriptor.dtype = "option" #if no values
        else:
        	descriptor.dtype = "text"

    session.commit()
    print("done; silly change")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('descriptors', 'dtype')
    ### end Alembic commands ###
