"""add dtype to descriptors

Revision ID: 4856a6d821b
Revises: None
Create Date: 2018-04-11 18:20:42.412042

"""

# revision identifiers, used by Alembic.
revision = '4856a6d821b'
down_revision = None

from sqlalchemy.orm import sessionmaker, Session as BaseSession, relationship
from app.models import Descriptor
from alembic import op
import sqlalchemy as sa

Session = sessionmaker()

def upgrade():
    bind = op.get_bind()
    session = Session(bind=bind)

    op.create_table('hyperlink_associations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('resource_id', sa.Integer(), nullable=True),
        sa.Column('descriptor_id', sa.Integer(), nullable=True),
        sa.Column('url', sa.String(length=250), nullable=True),
        sa.ForeignKeyConstraint(['descriptor_id'], ['descriptors.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # add d column
    op.add_column('descriptors', sa.Column('dtype', sa.String(length=15), nullable=True))

    for descriptor in session.query(Descriptor):
        if (descriptor.values):
        	descriptor.dtype = "option" #if no values
        else:
        	descriptor.dtype = "text"

    session.commit()
    print("done; added hyperlink table and dtype column")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hyperlink_associations')
    op.drop_column('descriptors', 'dtype')
    ### end Alembic commands ###
